services:
  # ==========================
  # ATTACKER (Kali Linux)
  # ==========================
  attacker:
    build:
      context: ./attacker
    container_name: attacker
    hostname: attacker

    tty: true
    stdin_open: true
    init: true

    cap_add:
      - NET_ADMIN
      - NET_RAW

    mem_limit: 768m
    mem_reservation: 512m
    cpus: "1.0"

    volumes:
      - /Users/mhdadam/SecLists:/opt/SecLists:ro

    restart: "no"

    networks:
      soc-net:
        ipv4_address: 172.19.0.2

  # ==========================
  # VICTIM SERVER (Ubuntu)
  # ==========================
  victim:
    build:
      context: ./victim
    container_name: victim-server
    hostname: victim-server

    init: true

    mem_limit: 512m
    mem_reservation: 384m
    cpus: "0.75"

    # Shared logs with Splunk
    volumes:
      - victim-logs:/shared-logs

    restart: "no"

    networks:
      soc-net:
        ipv4_address: 172.19.0.3

  # ==========================
  # SPLUNK ENTERPRISE
  # ==========================
  splunk:
    image: splunk/splunk:9.4
    container_name: splunk
    hostname: splunk

    # Starts only when requested
    profiles:
      - analysis

    environment:
      SPLUNK_START_ARGS: --accept-license
      SPLUNK_PASSWORD: CyberSOC123!
      SPLUNK_GENERAL_TERMS: --accept-sgt-current-at-splunk-com

    ports:
      - "8000:8000"
      - "8088:8088"
      - "9997:9997"

    # Same shared log folder as victim
    volumes:
      - victim-logs:/shared-logs

    mem_limit: 2g
    mem_reservation: 1200m
    cpus: "1.5"

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 15s
      retries: 30
      start_period: 180s

    restart: unless-stopped

    networks:
      soc-net:
        ipv4_address: 172.19.0.4

# ==========================
# NETWORK
# ==========================
networks:
  soc-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/24

# ==========================
# SHARED VOLUME FOR LIVE LOGS
# ==========================
volumes:
  victim-logs: